import { AWPFeature } from './types';

/** 功能依賴關係對照表：key 為子功能 ID，value 為父功能 ID */
export const DEPENDENCY_MAP: Record<string, string> = {
  TotalInMeterRate: 'SeparateMeterRate',
  TotalOutMeterRate: 'SeparateMeterRate',
  TotalPlayMeterRate: 'SeparateMeterRate',
  TotalWinMeterRate: 'SeparateMeterRate',
  CashoutLimitAmount: 'CashoutLimit',
  PlayScore: 'ScoreBox',
  HandCountAmount: 'HandCount',
};

/** YAML 匯出用的分類排序 */
export const CATEGORY_ORDER = [
  'SystemSetup.Configuration',
  'SystemSetup.JackpotSetting',
  'SystemSetup.TimeAdjust',
  'SystemSetup.VolumeSetting',
  'SystemSetup.PasswordSetting',
  'SystemSetup.PerGameName',
  'SystemSetup.PerGameBetList',
  'SystemSetup.PerGameDenomList',
  'Peripheral.BillAcceptorSetting',
  'Peripheral.PrinterSetting',
  'Peripheral.PrinterSetting.VoucherTemplate',
  'Peripheral.MeterSetting'
];

export const DEFAULT_FEATURES: AWPFeature[] = [
  // [SystemSetup] Configuration - Left
  {
    id: 'MaxPlay',
    nameEn: 'MAX. PLAY(TOTAL)',
    nameZh: '最大總投注',
    enabled: true,
    options: ['$3.00', '$4.00', '$5.00'],
    selectedOption: '$5.00',
    type: 'Combobox',
    description: '單次遊戲循環的最大允許總投注。',
    legalTip: '喬治亞州 B 類機台通常限制在 $5.00。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'MinPlay',
    nameEn: 'MIN. PLAY(TOTAL)',
    nameZh: '最小總投注',
    enabled: true,
    options: ['$0.25', '$0.50', '$1.00'],
    selectedOption: '$0.25',
    type: 'Combobox',
    description: '單次遊戲循環的最小允許總投注。',
    legalTip: '影響機台的最低入場門檻。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CashInUnit',
    nameEn: 'Cash In Unit',
    nameZh: '收幣單位',
    enabled: true,
    options: ['$0.01', '$0.02', '$0.05', '$0.10', '$0.20', '$0.25', '$0.50', '$1.00', '$2.00', '$5.00', '$10.00'],
    selectedOption: '$1.00',
    type: 'Combobox',
    description: '設定紙鈔機或投幣機的最小進存單位。',
    legalTip: '需與硬體收幣器設定同步。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'MeterRate',
    nameEn: 'Meter Rate',
    nameZh: '計數倍率',
    enabled: true,
    options: ['$1.00', '$1.25', '$1.50', '$2.00'],
    selectedOption: '$1.00',
    type: 'Combobox',
    description: '機械計數器進位一次代表的金額。',
    legalTip: '用於實體計數器的查帳基準。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CashOutUnit',
    nameEn: 'Cash Out Unit',
    nameZh: '出金單位',
    enabled: true,
    options: ['$0.01', '$0.04', '$0.05', '$0.10', '$0.15', '$0.20', '$0.25', '$0.50', '$0.75', '$1.00', '$2.00', '$5.00', '$10.00'],
    selectedOption: '$1.00',
    type: 'Combobox',
    description: '設定玩家出金時的最小貨幣單位。',
    legalTip: '影響機台的最低入場門檻。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'SpinBeforeCashout',
    nameEn: 'Spin Before Cashout',
    nameZh: '出金前旋轉',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '要求在出金前必須進行至少一次旋轉處理。',
    legalTip: '某些地區用於防止洗錢行為。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'ShowLastVoucher',
    nameEn: 'Show Last Voucher',
    nameZh: '顯示最後票據',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '在螢幕上顯示最後一張列印票據的資訊。',
    legalTip: '方便玩家和服務人員核對帳目。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CollectMode',
    nameEn: 'Collect Mode',
    nameZh: '收款模式',
    enabled: true,
    options: ['Printer', 'Attendant'],
    selectedOption: 'Printer',
    type: 'Combobox',
    description: '設定出金方式為票據列印或服務員人工派彩。',
    legalTip: '部分法令強制要求大額獎金須由服務員支付。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'DisplayFormat',
    nameEn: 'Display Format',
    nameZh: '顯示格式',
    enabled: true,
    options: ['Dollar', 'Credit'],
    selectedOption: 'Dollar',
    type: 'Combobox',
    description: '設定餘額顯示為金額或點數。',
    legalTip: '某些司法管轄區強制要求顯示真實貨幣金額。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CurrencySymbol',
    nameEn: 'Currency Symbol',
    nameZh: '貨幣符號',
    enabled: true,
    options: ['$', '¥', '€', 'None'],
    selectedOption: '$',
    type: 'Combobox',
    description: '顯示在金額前的貨幣符號。',
    legalTip: '需根據營運地區設定。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'AutoPlay',
    nameEn: 'Auto Play',
    nameZh: '自動遊戲',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '允許機台自動開始下一局遊戲。',
    legalTip: '在許多 AWP 市場中被禁止以防止被動賭博。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'ChanceLevel',
    nameEn: 'Chance Level',
    nameZh: '機率等級',
    enabled: true,
    options: ['Worse', 'Bad', 'Medium', 'Good', 'Best'],
    selectedOption: 'Medium',
    type: 'Combobox',
    description: '調整遊戲的波動性或中獎頻率。',
    legalTip: '必須符合認證的 RTP (玩家回報率) 範圍。',
    category: 'SystemSetup.Configuration'
  },

  // [SystemSetup] Configuration - Right
  {
    id: 'ScoreBox',
    nameEn: 'Score Box',
    nameZh: '得分框',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '在 UI 上顯示額外的得分統計框。',
    legalTip: '純視覺配置，無法律限制。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'PlayScore',
    nameEn: 'Play Score',
    nameZh: '遊戲得分',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '啟用或禁用遊戲得分顯示。',
    legalTip: '無特定法律限制。',
    category: 'SystemSetup.Configuration',
    dependsOn: 'ScoreBox'
  },
  {
    id: 'HandCount',
    nameEn: 'Hand Count',
    nameZh: '人工計數',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '啟用人工記錄遊戲局數的功能。',
    legalTip: '用於特定場所的合規性審計。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'HandCountAmount',
    nameEn: 'Hand Count Amount',
    nameZh: '人工計數金額',
    enabled: true,
    options: ['$1.00', '$5.00', '$10.00'],
    selectedOption: '$1.00',
    type: 'Combobox',
    description: '設定人工計數觸發的金額門檻。',
    legalTip: '與人工派彩門檻相關聯。',
    category: 'SystemSetup.Configuration',
    dependsOn: 'HandCount'
  },
  {
    id: 'ConfirmCashout',
    nameEn: 'Confirm Cashout',
    nameZh: '確認出金',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'ON',
    type: 'Switch',
    description: '出金前彈出確認視窗。',
    legalTip: '防止玩家誤觸出金按鈕。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'PrizeViewer',
    nameEn: 'Prize Viewer',
    nameZh: '獎金查看器',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '允許玩家查看可能的獎金組合。',
    legalTip: '增加遊戲透明度。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CashoutLimit',
    nameEn: 'Cashout Limit',
    nameZh: '出金限制',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '限制單次票據列印的最大金額處理。',
    legalTip: '超過此金額可能需要人工派彩處理。認證要求。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CashoutLimitAmount',
    nameEn: 'Cashout Limit Amount',
    nameZh: '出金限制金額',
    enabled: true,
    options: ['$1.00', '$10.00', '$50.00', '$100.00', '$500.00', '$1000.00'],
    selectedOption: '$10.00',
    type: 'Numberpad',
    description: '設定出金限制的具體金額。',
    legalTip: '通常設定為 $1,200 (IRS 申報門檻)。',
    category: 'SystemSetup.Configuration',
    dependsOn: 'CashoutLimit'
  },
  {
    id: 'MeterGame',
    nameEn: 'Meter Game',
    nameZh: '計數遊戲',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '啟用基於計數器的特殊遊戲模式。',
    legalTip: '需經過監管機構對遊戲邏輯的審核。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'MeterGameTimeouts',
    nameEn: 'Meter Game Timeouts',
    nameZh: '計數遊戲逾時',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'ON',
    type: 'Switch',
    description: '啟用計數遊戲在一段時間後的自動終結。',
    legalTip: '防止玩家長時間霸佔計數獎勵。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'MatchMeSkillGame',
    nameEn: 'Match Me Skill Game',
    nameZh: 'Match Me 技能遊戲',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '啟用 Match Me 技能型小遊戲。',
    legalTip: '喬治亞州 COAM Class B 強制要求。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'AttractMode',
    nameEn: 'Attract Mode',
    nameZh: '吸引模式',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'ON',
    type: 'Switch',
    description: '在機台閒置時播放展示動畫。',
    legalTip: '提高場內能見度。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'AttractSound',
    nameEn: 'Attract Sound',
    nameZh: '吸引音效',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'ON',
    type: 'Switch',
    description: '吸引模式下是否播放聲音。',
    legalTip: '受環境噪音法規或場所規定限制。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CurrentEnableGame',
    nameEn: 'Current Enable Game',
    nameZh: '當前啟用遊戲數',
    enabled: true,
    options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    selectedOption: '5',
    type: 'Combobox',
    description: '機台目前啟用的遊戲數量 (最大 10)。',
    legalTip: '需配合營運授權與機台效能。',
    category: 'SystemSetup.Configuration'
  },

  // PerGameName
  {
    id: 'game1_name',
    nameEn: 'Game 1 Name',
    nameZh: '遊戲 1 名稱',
    enabled: true,
    options: ['MoneyPotDeluxe'],
    selectedOption: 'MoneyPotDeluxe',
    type: 'Textfield',
    description: '遊戲 1 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game2_name',
    nameEn: 'Game 2 Name',
    nameZh: '遊戲 2 名稱',
    enabled: true,
    options: ['CoinNonet'],
    selectedOption: 'CoinNonet',
    type: 'Textfield',
    description: '遊戲 2 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game3_name',
    nameEn: 'Game 3 Name',
    nameZh: '遊戲 3 名稱',
    enabled: true,
    options: ['DevilsTreasures2'],
    selectedOption: 'DevilsTreasures2',
    type: 'Textfield',
    description: '遊戲 3 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game4_name',
    nameEn: 'Game 4 Name',
    nameZh: '遊戲 4 名稱',
    enabled: true,
    options: ['MoneyComing'],
    selectedOption: 'MoneyComing',
    type: 'Textfield',
    description: '遊戲 4 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game5_name',
    nameEn: 'Game 5 Name',
    nameZh: '遊戲 5 名稱',
    enabled: true,
    options: ['Shooting4'],
    selectedOption: 'Shooting4',
    type: 'Textfield',
    description: '遊戲 5 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game6_name',
    nameEn: 'Game 6 Name',
    nameZh: '遊戲 6 名稱',
    enabled: true,
    options: [''],
    selectedOption: '',
    type: 'Textfield',
    description: '遊戲 6 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game7_name',
    nameEn: 'Game 7 Name',
    nameZh: '遊戲 7 名稱',
    enabled: true,
    options: [''],
    selectedOption: '',
    type: 'Textfield',
    description: '遊戲 7 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game8_name',
    nameEn: 'Game 8 Name',
    nameZh: '遊戲 8 名稱',
    enabled: true,
    options: [''],
    selectedOption: '',
    type: 'Textfield',
    description: '遊戲 8 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game9_name',
    nameEn: 'Game 9 Name',
    nameZh: '遊戲 9 名稱',
    enabled: true,
    options: [''],
    selectedOption: '',
    type: 'Textfield',
    description: '遊戲 9 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },
  {
    id: 'game10_name',
    nameEn: 'Game 10 Name',
    nameZh: '遊戲 10 名稱',
    enabled: true,
    options: [''],
    selectedOption: '',
    type: 'Textfield',
    description: '遊戲 10 的顯示名稱。',
    legalTip: '最長 63 個字元。',
    category: 'SystemSetup.PerGameName'
  },

  // PerGameBetList
  {
    id: 'game1_bets',
    nameEn: 'Game 1 Bets',
    nameZh: '遊戲 1 投注清單',
    enabled: true,
    options: ['20', '30', '50', '80', '100', '150', '200', '250', '300', '400', '500'],
    selectedOption: '20',
    type: 'Combobox',
    description: '遊戲 1 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game2_bets',
    nameEn: 'Game 2 Bets',
    nameZh: '遊戲 2 投注清單',
    enabled: true,
    options: ['20', '30', '50', '80', '100', '150', '200', '250', '300', '400', '500'],
    selectedOption: '20',
    type: 'Combobox',
    description: '遊戲 2 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game3_bets',
    nameEn: 'Game 3 Bets',
    nameZh: '遊戲 3 投注清單',
    enabled: true,
    options: ['20', '30', '50', '80', '100', '150', '200', '250', '300', '400', '500'],
    selectedOption: '20',
    type: 'Combobox',
    description: '遊戲 3 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game4_bets',
    nameEn: 'Game 4 Bets',
    nameZh: '遊戲 4 投注清單',
    enabled: true,
    options: ['1', '5', '10', '50', '100'],
    selectedOption: '1',
    type: 'Combobox',
    description: '遊戲 4 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game5_bets',
    nameEn: 'Game 5 Bets',
    nameZh: '遊戲 5 投注清單',
    enabled: true,
    options: ['20', '30', '50', '80', '100', '150', '200', '250', '300', '400', '500'],
    selectedOption: '20',
    type: 'Combobox',
    description: '遊戲 5 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game6_bets',
    nameEn: 'Game 6 Bets',
    nameZh: '遊戲 6 投注清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 6 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game7_bets',
    nameEn: 'Game 7 Bets',
    nameZh: '遊戲 7 投注清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 7 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game8_bets',
    nameEn: 'Game 8 Bets',
    nameZh: '遊戲 8 投注清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 8 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game9_bets',
    nameEn: 'Game 9 Bets',
    nameZh: '遊戲 9 投注清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 9 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },
  {
    id: 'game10_bets',
    nameEn: 'Game 10 Bets',
    nameZh: '遊戲 10 投注清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 10 可用的投注選項。',
    legalTip: '必須包含在認證範圍內。',
    category: 'SystemSetup.PerGameBetList'
  },

  // PerGameDenomList
  {
    id: 'game1_denoms',
    nameEn: 'Game 1 Denoms',
    nameZh: '遊戲 1 面額清單',
    enabled: true,
    options: ['1'],
    selectedOption: '1',
    type: 'Combobox',
    description: '遊戲 1 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game2_denoms',
    nameEn: 'Game 2 Denoms',
    nameZh: '遊戲 2 面額清單',
    enabled: true,
    options: ['1'],
    selectedOption: '1',
    type: 'Combobox',
    description: '遊戲 2 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game3_denoms',
    nameEn: 'Game 3 Denoms',
    nameZh: '遊戲 3 面額清單',
    enabled: true,
    options: ['1'],
    selectedOption: '1',
    type: 'Combobox',
    description: '遊戲 3 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game4_denoms',
    nameEn: 'Game 4 Denoms',
    nameZh: '遊戲 4 面額清單',
    enabled: true,
    options: ['10'],
    selectedOption: '10',
    type: 'Combobox',
    description: '遊戲 4 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game5_denoms',
    nameEn: 'Game 5 Denoms',
    nameZh: '遊戲 5 面額清單',
    enabled: true,
    options: ['1'],
    selectedOption: '1',
    type: 'Combobox',
    description: '遊戲 5 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game6_denoms',
    nameEn: 'Game 6 Denoms',
    nameZh: '遊戲 6 面額清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 6 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game7_denoms',
    nameEn: 'Game 7 Denoms',
    nameZh: '遊戲 7 面額清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 7 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game8_denoms',
    nameEn: 'Game 8 Denoms',
    nameZh: '遊戲 8 面額清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 8 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game9_denoms',
    nameEn: 'Game 9 Denoms',
    nameZh: '遊戲 9 面額清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 9 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },
  {
    id: 'game10_denoms',
    nameEn: 'Game 10 Denoms',
    nameZh: '遊戲 10 面額清單',
    enabled: true,
    options: [],
    selectedOption: '',
    type: 'Combobox',
    description: '遊戲 10 可用的面額 (cents)。',
    legalTip: '需對應機台支援的面額。',
    category: 'SystemSetup.PerGameDenomList'
  },

  // Jackpot Setting
  {
    id: 'JpMinMaxInfo',
    nameEn: 'Grand Jackpot Range',
    nameZh: '累積大獎範圍',
    enabled: true,
    options: ['$500.00 ~ $1200.00', '$1000.00 ~ $2500.00', '$1250.00 ~ $3500.00', '$1250.00 ~ $5000.00', '$2500.00 ~ $6250.00', '$3000.00 ~ $7500.00', '$4000.00 ~ $10000.00'],
    selectedOption: '$500.00 ~ $1200.00',
    type: 'Combobox',
    description: '設定累積大獎 (Grand) 的隨機觸發範圍。',
    legalTip: '某些司法管轄區對最高累積獎金有嚴格限制。',
    category: 'SystemSetup.JackpotSetting'
  },
  {
    id: 'JpMinMaxInfo_Major',
    nameEn: 'Major Jackpot Range',
    nameZh: '二獎累計範圍',
    enabled: true,
    options: ['$500.00 ~ $1200.00', '$1000.00 ~ $2500.00', '$1250.00 ~ $3500.00'],
    selectedOption: '$500.00 ~ $1200.00',
    type: 'Combobox',
    description: '設定二獎 (Major) 的隨機觸發範圍。',
    legalTip: '通常為 Grand 的子集或較低門檻。',
    category: 'SystemSetup.JackpotSetting'
  },
  {
    id: 'JpMinMaxInfo_Minor',
    nameEn: 'Minor Jackpot Range',
    nameZh: '三獎累計範圍',
    enabled: true,
    options: ['$500.00 ~ $1200.00', '$1000.00 ~ $2500.00'],
    selectedOption: '$500.00 ~ $1200.00',
    type: 'Combobox',
    description: '設定三獎 (Minor) 的隨機觸發範圍。',
    legalTip: '通常為固定倍數或小型 Progressive。',
    category: 'SystemSetup.JackpotSetting'
  },
  {
    id: 'JpMinBetForJp',
    nameEn: 'Min Play For Jp',
    nameZh: '彩金最低投注',
    enabled: true,
    options: ['$0.25', '$0.50', '$1.00', '$1.50', '$2.00'],
    selectedOption: '$0.25',
    type: 'Combobox',
    description: '獲得累積獎金資格所需的最低投注額。',
    legalTip: '必須在遊戲說明中明確標示最低投注要求。',
    category: 'SystemSetup.JackpotSetting'
  },
  {
    id: 'GrandJpInitValue',
    nameEn: 'Grand Jp Init Value',
    nameZh: '大獎起始值',
    enabled: true,
    options: ['$1000.00'],
    selectedOption: '$1000.00',
    type: 'Numberpad',
    description: 'Grand Jackpot 重置後的保底金額。',
    legalTip: '不能低於法律規定的保底值。',
    category: 'SystemSetup.JackpotSetting'
  },
  {
    id: 'MajorJpInitValue',
    nameEn: 'Major Jp Init Value',
    nameZh: '二獎起始值',
    enabled: true,
    options: ['$100.00'],
    selectedOption: '$100.00',
    type: 'Numberpad',
    description: 'Major Jackpot 重置後的保底金額。',
    legalTip: '通常為 Grand 的 10%。',
    category: 'SystemSetup.JackpotSetting'
  },
  {
    id: 'MinorJpInitValue',
    nameEn: 'Minor Jp Init Value',
    nameZh: '三獎起始值',
    enabled: true,
    options: ['$10.00'],
    selectedOption: '$10.00',
    type: 'Numberpad',
    description: 'Minor Jackpot 的初始金額。',
    legalTip: '通常是固定面額獎勵。',
    category: 'SystemSetup.JackpotSetting'
  },

  // Printer Template
  {
    id: 'Location',
    nameEn: 'Location',
    nameZh: '場館名稱',
    enabled: true,
    options: ['AWP Casino'],
    selectedOption: 'AWP Casino',
    type: 'Textfield',
    description: '票據上顯示的場地或賭場名稱。',
    legalTip: '必須與營業執照登記名稱一致。',
    category: 'Peripheral.PrinterSetting'
  },
  {
    id: 'Address1',
    nameEn: 'Address 1',
    nameZh: '地址 1',
    enabled: true,
    options: ['Street 123'],
    selectedOption: 'Street 123',
    type: 'Textfield',
    description: '票據上顯示的地址第一行。',
    legalTip: '依法需提供準確的地點資訊。',
    category: 'Peripheral.PrinterSetting'
  },
  {
    id: 'VoucherMessage1',
    nameEn: 'Voucher Message 1',
    nameZh: '票據訊息 1',
    enabled: true,
    options: ['NO CASH VALUE'],
    selectedOption: 'NO CASH VALUE',
    type: 'Textfield',
    description: '票據底部的法律免責或活動訊息。',
    legalTip: '通常強制包含 "NO CASH VALUE" 或類似警語。',
    category: 'Peripheral.PrinterSetting'
  },
  {
    id: 'CounterSpeed',
    nameEn: 'Counter Speed',
    nameZh: '計數器速度',
    enabled: true,
    options: ['Normal', 'Medium', 'Fastest'],
    selectedOption: 'Normal',
    type: 'Spinbox',
    description: '控制實體計數器跳動的物理速度。',
    legalTip: '旨在平衡聽覺回饋與硬體壽命。',
    category: 'Peripheral.MeterSetting'
  },
  {
    id: 'AwardLimitAmount',
    nameEn: 'Award Limit Amount',
    nameZh: '獎勵限制金額',
    enabled: true,
    options: ['Off', '$500.00', '$1000.00', '$1200.00', '$1500.00', '$1800.00', '$2000.00'],
    selectedOption: 'Off',
    type: 'Combobox',
    description: '單次贏分超過此金額時，需由服務員派彩。',
    legalTip: '常用於 $1,200 報稅門檻。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'BalanceLimitAmount',
    nameEn: 'Balance Limit Amount',
    nameZh: '餘額限制金額',
    enabled: true,
    options: ['Off', '$10.00', '$20.00'],
    selectedOption: 'Off',
    type: 'Combobox',
    description: '限制機台內可保留的最大餘額。',
    legalTip: '某些地區法律規定。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CoinInUnit',
    nameEn: 'Coin In Unit',
    nameZh: '投幣單位',
    enabled: true,
    options: ['$0.01', '$0.02', '$0.05', '$0.10', '$0.20', '$0.25', '$0.50', '$1.00', '$2.00', '$5.00', '$10.00'],
    selectedOption: '$1.00',
    type: 'Combobox',
    description: '設定投幣機的進存單位。',
    legalTip: '需配合實體投幣器規格。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'KeyInOutMode',
    nameEn: 'Key In/Out Mode',
    nameZh: '開分/洗分模式',
    enabled: true,
    options: ['Off', 'KeyOutOnly', 'KeyInOut'],
    selectedOption: 'Off',
    type: 'Combobox',
    description: '設定手動開洗分的權限模式。',
    legalTip: '用於場所查帳與點券管理。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'KeyInUnit',
    nameEn: 'Key In Unit',
    nameZh: '開分單位',
    enabled: true,
    options: ['$0.01', '$0.02', '$0.10', '$0.50', '$1.00', '$5.00', '$10.00'],
    selectedOption: '$1.00',
    type: 'Combobox',
    description: '手動開分時每次跳動的金額單位。',
    legalTip: '與場所運作邏輯一致。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'SeparateMeterRate',
    nameEn: 'Separate Meter Rate',
    nameZh: '分離計數倍率',
    enabled: true,
    options: ['OFF', 'ON'],
    selectedOption: 'OFF',
    type: 'Switch',
    description: '是否為不同類型的帳目設定獨立的計數倍率。',
    legalTip: '高度自定義的查帳配置。',
    category: 'SystemSetup.Configuration'
  },
  {
    id: 'CreditDenom',
    nameEn: 'Credit Denom',
    nameZh: '分數面額',
    enabled: true,
    options: ['10', '50', '100', '200', '500', '1000', '2000', '5000', '10000'],
    selectedOption: '100',
    type: 'Combobox',
    description: '設定機台的分數與金額對應比率。',
    legalTip: '影響玩家感知的輸贏速度。',
    category: 'SystemSetup.Configuration'
  }
];
